import { CompleteMaintenanceInputSchema,CreateMaintenanceInputSchema,MaintenanceListQuerySchema,UpdateMaintenanceInputSchema } from 'shared';
import type { CompleteMaintenanceInput,CreateMaintenanceInput,MaintenanceListQuery,MaintenanceRecord,MaintenanceSummary,UpdateMaintenanceInput } from 'shared';
import { AppError } from '../middleware/errorHandler';
import type { IMaintenanceRepository } from '../repositories/MaintenanceRepository';
const clean=(v:string|null|undefined)=>v===undefined||v===null?v:v.trim()||null;
const terminal=['COMPLETED','CANCELLED','BEYOND_REPAIR'];
export interface IMaintenanceService {list(q:MaintenanceListQuery):Promise<MaintenanceRecord[]>;get(id:number):Promise<MaintenanceRecord>;create(i:CreateMaintenanceInput):Promise<MaintenanceRecord>;update(id:number,i:UpdateMaintenanceInput):Promise<MaintenanceRecord>;start(id:number,i:UpdateMaintenanceInput):Promise<MaintenanceRecord>;waiting(id:number,i:UpdateMaintenanceInput):Promise<MaintenanceRecord>;complete(id:number,i:CompleteMaintenanceInput):Promise<MaintenanceRecord>;cancel(id:number):Promise<MaintenanceRecord>;beyondRepair(id:number,i:UpdateMaintenanceInput):Promise<MaintenanceRecord>;history(assetId:number):Promise<MaintenanceRecord[]>;summary():Promise<MaintenanceSummary>}
export class MaintenanceService implements IMaintenanceService {
 constructor(private readonly repo:IMaintenanceRepository){}
 async list(q:MaintenanceListQuery){return this.repo.listMaintenanceRecords(MaintenanceListQuerySchema.parse(q));}
 async get(id:number){const r=await this.repo.getMaintenanceById(id);if(!r)throw new AppError('Maintenance record not found',404);return r;}
 async create(i:CreateMaintenanceInput){const p=CreateMaintenanceInputSchema.parse(i);const a=await this.repo.getAsset(p.assetId);if(!a||a.archivedAt)throw new AppError('Asset not found',404);if(a.status==='DISPOSED')throw new AppError('Disposed assets cannot receive maintenance',400);return this.repo.createMaintenance({...p,assignedTechnician:clean(p.assignedTechnician),vendor:clean(p.vendor),faultDescription:clean(p.faultDescription),notes:clean(p.notes)});}
 async update(id:number,i:UpdateMaintenanceInput){const r=await this.get(id);if(terminal.includes(r.status))throw new AppError('Terminal maintenance records are read-only',409);const p=UpdateMaintenanceInputSchema.parse(i);if(Object.keys(p).length===0)throw new AppError('At least one usable field is required',400);if(p.scheduledDate&&p.scheduledDate<r.reportedDate)throw new AppError('Scheduled date cannot be before reported date',400);return this.repo.updateMaintenance(id,this.normalize(p));}
 async start(id:number,i:UpdateMaintenanceInput){const r=await this.get(id);if(!['REPORTED','SCHEDULED','WAITING_FOR_PARTS'].includes(r.status))throw new AppError('Maintenance cannot start in its current state',409);const p=UpdateMaintenanceInputSchema.parse(i);if(!p.startedDate)throw new AppError('Start date is required',400);if(p.startedDate<r.reportedDate)throw new AppError('Start date cannot be before reported date',400);return this.repo.startMaintenance(id,this.normalize(p));}
 async waiting(id:number,i:UpdateMaintenanceInput){const r=await this.get(id);if(r.status!=='IN_PROGRESS')throw new AppError('Only in-progress maintenance can wait for parts',409);return this.repo.markWaitingForParts(id,this.normalize(UpdateMaintenanceInputSchema.parse(i)));}
 async complete(id:number,i:CompleteMaintenanceInput){const r=await this.get(id);if(!['IN_PROGRESS','WAITING_FOR_PARTS'].includes(r.status))throw new AppError(r.status==='COMPLETED'?'Maintenance is already completed':'Maintenance cannot be completed in its current state',409);const p=CompleteMaintenanceInputSchema.parse(i);if(!r.startedDate||p.completedDate<r.startedDate)throw new AppError('Completion date cannot be before start date',400);return this.repo.completeMaintenance(id,{...p,partsUsed:clean(p.partsUsed),notes:clean(p.notes)});}
 async cancel(id:number){const r=await this.get(id);if(terminal.includes(r.status))throw new AppError('Maintenance cannot be cancelled in its current state',409);return this.repo.cancelMaintenance(id);}
 async beyondRepair(id:number,i:UpdateMaintenanceInput){const r=await this.get(id);if(!['IN_PROGRESS','WAITING_FOR_PARTS'].includes(r.status))throw new AppError('Maintenance cannot be marked beyond repair in its current state',409);return this.repo.markBeyondRepair(id,this.normalize(UpdateMaintenanceInputSchema.parse(i)));}
 async history(assetId:number){const a=await this.repo.getAsset(assetId);if(!a||a.archivedAt)throw new AppError('Asset not found',404);return this.repo.listMaintenanceHistoryForAsset(assetId);}
 async summary(){return this.repo.calculateMaintenanceSummary();}
 private normalize(i:UpdateMaintenanceInput):UpdateMaintenanceInput{const n={...i};for(const k of ['assignedTechnician','vendor','faultDescription','diagnosis','workPerformed','partsUsed','resolution','notes'] as const)if(i[k]!==undefined)n[k]=clean(i[k]);return n;}
}
