import type Database from 'better-sqlite3';
import type { CompleteMaintenanceInput,CreateMaintenanceInput,MaintenanceListQuery,MaintenanceRecord,MaintenanceSummary,UpdateMaintenanceInput } from 'shared';
import { getCurrentDb } from '../database/connection';

interface Row { id:number;maintenance_number:string;asset_id:number;maintenance_type:MaintenanceRecord['maintenanceType'];priority:MaintenanceRecord['priority'];status:MaintenanceRecord['status'];reported_date:string;scheduled_date:string|null;started_date:string|null;completed_date:string|null;reported_by_person_id:number|null;assigned_technician:string|null;vendor:string|null;fault_description:string|null;diagnosis:string|null;work_performed:string|null;parts_used:string|null;maintenance_cost:number;downtime_hours:number;condition_before:MaintenanceRecord['conditionBefore'];condition_after:MaintenanceRecord['conditionAfter'];resolution:string|null;notes:string|null;created_at:string;updated_at:string;archived_at:string|null;asset_tag:string;manufacturer:string;model:string;serial_number:string|null;asset_status:MaintenanceRecord['assetStatus'];reporter_name:string|null }
const select=`SELECT m.*,a.asset_tag,a.manufacturer,a.model,a.serial_number,a.status asset_status,CASE WHEN p.id IS NULL THEN NULL ELSE p.first_name||' '||p.last_name END reporter_name FROM maintenance_records m JOIN assets a ON a.id=m.asset_id LEFT JOIN people p ON p.id=m.reported_by_person_id`;
const map=(r:Row):MaintenanceRecord=>({id:r.id,maintenanceNumber:r.maintenance_number,assetId:r.asset_id,maintenanceType:r.maintenance_type,priority:r.priority,status:r.status,reportedDate:r.reported_date,scheduledDate:r.scheduled_date,startedDate:r.started_date,completedDate:r.completed_date,reportedByPersonId:r.reported_by_person_id,assignedTechnician:r.assigned_technician,vendor:r.vendor,faultDescription:r.fault_description,diagnosis:r.diagnosis,workPerformed:r.work_performed,partsUsed:r.parts_used,maintenanceCost:r.maintenance_cost,downtimeHours:r.downtime_hours,conditionBefore:r.condition_before,conditionAfter:r.condition_after,resolution:r.resolution,notes:r.notes,createdAt:r.created_at,updatedAt:r.updated_at,archivedAt:r.archived_at,assetTag:r.asset_tag,assetManufacturer:r.manufacturer,assetModel:r.model,assetSerialNumber:r.serial_number,assetStatus:r.asset_status,reporterName:r.reporter_name});

export interface IMaintenanceRepository {
 listMaintenanceRecords(q:MaintenanceListQuery):Promise<MaintenanceRecord[]>;getMaintenanceById(id:number):Promise<MaintenanceRecord|null>;getMaintenanceByNumber(n:string):Promise<MaintenanceRecord|null>;
 createMaintenance(i:CreateMaintenanceInput):Promise<MaintenanceRecord>;updateMaintenance(id:number,i:UpdateMaintenanceInput):Promise<MaintenanceRecord>;
 startMaintenance(id:number,i:UpdateMaintenanceInput):Promise<MaintenanceRecord>;completeMaintenance(id:number,i:CompleteMaintenanceInput):Promise<MaintenanceRecord>;
 cancelMaintenance(id:number):Promise<MaintenanceRecord>;markWaitingForParts(id:number,i:UpdateMaintenanceInput):Promise<MaintenanceRecord>;
 markBeyondRepair(id:number,i:UpdateMaintenanceInput):Promise<MaintenanceRecord>;archiveMaintenance(id:number):Promise<void>;
 listMaintenanceHistoryForAsset(id:number):Promise<MaintenanceRecord[]>;countMaintenanceByStatus():Promise<Record<string,number>>;calculateMaintenanceSummary():Promise<MaintenanceSummary>;
 getAsset(id:number):Promise<{id:number;status:string;archivedAt:string|null}|null>;
}

export class MaintenanceRepository implements IMaintenanceRepository {
 constructor(private readonly db:Database.Database=getCurrentDb()){}
 async listMaintenanceRecords(q:MaintenanceListQuery){const c=['m.archived_at IS NULL'];const p:Record<string,string|number>={};if(q.search){c.push('(m.maintenance_number LIKE @search OR a.asset_tag LIKE @search OR a.manufacturer LIKE @search OR a.model LIKE @search OR m.fault_description LIKE @search)');p.search=`%${q.search}%`;}for(const [k,col] of [['assetId','m.asset_id'],['maintenanceType','m.maintenance_type'],['priority','m.priority'],['status','m.status']] as const)if(q[k]!==undefined){c.push(`${col}=@${k}`);p[k]=q[k];}for(const [k,col] of [['assignedTechnician','m.assigned_technician'],['vendor','m.vendor']] as const)if(q[k]){c.push(`${col} LIKE @${k}`);p[k]=`%${q[k]}%`;}for(const [k,col,op] of [['reportedFrom','m.reported_date','>='],['reportedTo','m.reported_date','<='],['scheduledFrom','m.scheduled_date','>='],['scheduledTo','m.scheduled_date','<=']] as const)if(q[k]){c.push(`${col}${op}@${k}`);p[k]=q[k];}if(q.overdueOnly)c.push("m.status IN ('REPORTED','SCHEDULED') AND m.scheduled_date<date('now')");const cols={reportedDate:'m.reported_date',scheduledDate:'m.scheduled_date',priority:'m.priority',status:'m.status',updatedAt:'m.updated_at'} as const;p.limit=q.pageSize??20;p.offset=((q.page??1)-1)*(q.pageSize??20);const rows=this.db.prepare(`${select} WHERE ${c.join(' AND ')} ORDER BY ${cols[q.sortBy??'reportedDate']} ${q.sortOrder==='asc'?'ASC':'DESC'},m.id DESC LIMIT @limit OFFSET @offset`).all(p) as Row[];return rows.map(map);}
 async getMaintenanceById(id:number){const r=this.db.prepare(`${select} WHERE m.id=? AND m.archived_at IS NULL`).get(id) as Row|undefined;return r?map(r):null;}
 async getMaintenanceByNumber(n:string){const r=this.db.prepare(`${select} WHERE m.maintenance_number=? AND m.archived_at IS NULL`).get(n) as Row|undefined;return r?map(r):null;}
 async createMaintenance(i:CreateMaintenanceInput){const id=this.db.transaction(()=>{const year=i.reportedDate.slice(0,4);const prefix=`MNT-${year}-`;const last=this.db.prepare('SELECT maintenance_number FROM maintenance_records WHERE maintenance_number LIKE ? ORDER BY maintenance_number DESC LIMIT 1').get(`${prefix}%`) as {maintenance_number:string}|undefined;const seq=last?Number(last.maintenance_number.slice(-4))+1:1;const number=`${prefix}${String(seq).padStart(4,'0')}`;const status=i.scheduledDate?'SCHEDULED':'REPORTED';return Number(this.db.prepare(`INSERT INTO maintenance_records(maintenance_number,asset_id,maintenance_type,priority,status,reported_date,scheduled_date,reported_by_person_id,assigned_technician,vendor,fault_description,notes) VALUES(@number,@assetId,@maintenanceType,@priority,@status,@reportedDate,@scheduledDate,@reportedByPersonId,@assignedTechnician,@vendor,@faultDescription,@notes)`).run({...i,number,status,scheduledDate:i.scheduledDate??null,reportedByPersonId:i.reportedByPersonId??null,assignedTechnician:i.assignedTechnician??null,vendor:i.vendor??null,faultDescription:i.faultDescription??null,notes:i.notes??null}).lastInsertRowid);})();return this.required(id);}
 async updateMaintenance(id:number,i:UpdateMaintenanceInput){this.dynamicUpdate(id,i);return this.required(id);}
 async startMaintenance(id:number,i:UpdateMaintenanceInput){this.db.transaction(()=>{this.dynamicUpdateSync(id,{...i});this.db.prepare("UPDATE maintenance_records SET status='IN_PROGRESS',updated_at=datetime('now') WHERE id=?").run(id);const r=this.db.prepare('SELECT asset_id,maintenance_type FROM maintenance_records WHERE id=?').get(id) as {asset_id:number;maintenance_type:string};if(r.maintenance_type==='CORRECTIVE')this.db.prepare("UPDATE assets SET status='UNDER_REPAIR',updated_at=datetime('now') WHERE id=?").run(r.asset_id);})();return this.required(id);}
 async markWaitingForParts(id:number,i:UpdateMaintenanceInput){this.db.transaction(()=>{this.dynamicUpdateSync(id,i);this.db.prepare("UPDATE maintenance_records SET status='WAITING_FOR_PARTS',updated_at=datetime('now') WHERE id=?").run(id);})();return this.required(id);}
 async completeMaintenance(id:number,i:CompleteMaintenanceInput){this.db.transaction(()=>{const r=this.db.prepare('SELECT asset_id FROM maintenance_records WHERE id=?').get(id) as {asset_id:number};this.db.prepare(`UPDATE maintenance_records SET status='COMPLETED',completed_date=@completedDate,work_performed=@workPerformed,parts_used=@partsUsed,maintenance_cost=@maintenanceCost,downtime_hours=@downtimeHours,condition_after=@conditionAfter,resolution=@resolution,notes=COALESCE(@notes,notes),updated_at=datetime('now') WHERE id=@id`).run({...i,id,partsUsed:i.partsUsed??null,notes:i.notes??null});this.restoreAsset(r.asset_id,i.conditionAfter);})();return this.required(id);}
 async cancelMaintenance(id:number){this.db.transaction(()=>{const r=this.db.prepare('SELECT asset_id FROM maintenance_records WHERE id=?').get(id) as {asset_id:number};this.db.prepare("UPDATE maintenance_records SET status='CANCELLED',updated_at=datetime('now') WHERE id=?").run(id);this.restoreAsset(r.asset_id,null);})();return this.required(id);}
 async markBeyondRepair(id:number,i:UpdateMaintenanceInput){this.db.transaction(()=>{this.dynamicUpdateSync(id,i);const r=this.db.prepare('SELECT asset_id FROM maintenance_records WHERE id=?').get(id) as {asset_id:number};this.db.prepare("UPDATE maintenance_records SET status='BEYOND_REPAIR',completed_date=COALESCE(completed_date,date('now')),updated_at=datetime('now') WHERE id=?").run(id);this.db.prepare("UPDATE assets SET status='RETIRED',condition='DAMAGED',updated_at=datetime('now') WHERE id=?").run(r.asset_id);})();return this.required(id);}
 async archiveMaintenance(id:number){this.db.prepare("UPDATE maintenance_records SET archived_at=datetime('now') WHERE id=?").run(id);}
 async listMaintenanceHistoryForAsset(id:number){return this.listMaintenanceRecords({assetId:id,pageSize:100});}
 async countMaintenanceByStatus(){const rows=this.db.prepare('SELECT status,count(*) count FROM maintenance_records WHERE archived_at IS NULL GROUP BY status').all() as {status:string;count:number}[];return Object.fromEntries(rows.map(r=>[r.status,r.count]));}
 async calculateMaintenanceSummary(){const row=this.db.prepare(`SELECT COALESCE(SUM(CASE WHEN status NOT IN ('COMPLETED','CANCELLED','BEYOND_REPAIR') THEN 1 ELSE 0 END),0) openRequests,COALESCE(SUM(status='SCHEDULED'),0) scheduled,COALESCE(SUM(status='IN_PROGRESS'),0) inProgress,COALESCE(SUM(status='WAITING_FOR_PARTS'),0) waitingForParts,COALESCE(SUM(status='COMPLETED' AND substr(completed_date,1,7)=strftime('%Y-%m','now')),0) completedThisMonth,COALESCE(SUM(priority='CRITICAL' AND status NOT IN ('COMPLETED','CANCELLED','BEYOND_REPAIR')),0) criticalPriority,COALESCE(SUM(CASE WHEN substr(completed_date,1,7)=strftime('%Y-%m','now') THEN maintenance_cost ELSE 0 END),0) totalCostThisMonth FROM maintenance_records WHERE archived_at IS NULL`).get() as MaintenanceSummary;return row;}
 async getAsset(id:number){const r=this.db.prepare('SELECT id,status,archived_at FROM assets WHERE id=?').get(id) as {id:number;status:string;archived_at:string|null}|undefined;return r?{id:r.id,status:r.status,archivedAt:r.archived_at}:null;}
 private async required(id:number){const r=await this.getMaintenanceById(id);if(!r)throw new Error('Maintenance record could not be loaded');return r;}
 private dynamicUpdate(id:number,i:UpdateMaintenanceInput){this.dynamicUpdateSync(id,i);}
 private dynamicUpdateSync(id:number,i:UpdateMaintenanceInput){const cols:Record<keyof UpdateMaintenanceInput,string>={scheduledDate:'scheduled_date',assignedTechnician:'assigned_technician',vendor:'vendor',faultDescription:'fault_description',diagnosis:'diagnosis',workPerformed:'work_performed',partsUsed:'parts_used',maintenanceCost:'maintenance_cost',downtimeHours:'downtime_hours',conditionBefore:'condition_before',conditionAfter:'condition_after',resolution:'resolution',notes:'notes',startedDate:'started_date'};const f:string[]=[];const p:Record<string,string|number|null>={id};for(const k of Object.keys(i) as (keyof UpdateMaintenanceInput)[]){f.push(`${cols[k]}=@${k}`);p[k]=i[k]??null;}if(f.length===0)return;this.db.prepare(`UPDATE maintenance_records SET ${f.join(',')},updated_at=datetime('now') WHERE id=@id`).run(p);}
 private restoreAsset(assetId:number,condition:string|null){const active=this.db.prepare("SELECT assignment_type FROM asset_assignments WHERE asset_id=? AND status='ACTIVE' AND archived_at IS NULL").get(assetId) as {assignment_type:string}|undefined;const status=active?(active.assignment_type==='LOCATION'?'DEPLOYED':'ASSIGNED'):'IN_STOCK';this.db.prepare('UPDATE assets SET status=?,condition=COALESCE(?,condition),updated_at=datetime(\'now\') WHERE id=?').run(status,condition,assetId);}
}
export const createMaintenanceRepository=(db?:Database.Database):IMaintenanceRepository=>new MaintenanceRepository(db);
